//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int Id { get; set; }
        public System.Guid MenuFolderGUID { get; set; }
        public System.Guid RowGUID { get; set; }
        public Nullable<int> UnitCount { get; set; }
        public Nullable<System.Guid> UnitGUID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
        public int RowPosition { get; set; }
    }
}
