//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDishIngredient
    {
        public int Id { get; set; }
        public System.Guid DishGUID { get; set; }
        public System.Guid IngredientGUID { get; set; }
        public int Count { get; set; }
        public System.Guid OrderGUID { get; set; }
    }
}
