//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TimeOn { get; set; }
        public Nullable<System.DateTime> TimeOff { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> RndOrderNum_Date { get; set; }
        public Nullable<int> RndOrderNum_InitVal { get; set; }
        public Nullable<int> RndOrderNum_NextVal { get; set; }
    }
}
